Replaced the RHEL init script for asynchronous publishing

diff --git a/bin/startup/rhel/asynchronous-publishing b/bin/startup/rhel/asynchronous-publishing
--- a/bin/startup/rhel/asynchronous-publishing
+++ b/bin/startup/rhel/asynchronous-publishing
@@ -1,129 +1,129 @@
-#!/bin/bash
+#!/bin/sh
 #
-# eZ Publish asychronous publishing init script for RHEL and CENTOS.
+# ezpqp        eZ Publish asychronous publishing init script for RHEL and SLES
 #
-# Usage:
-#
-# Set the correct SOLR_HOME value, and copy this file to /etc/init.d
-# Symlink to /etc/init.d/solr to /etc/rc3.d/S70ezpublish and /etc/rc5.d/S70publish
-#
-# Example:
-# cp solr /etc/init.d/solr
-# cd /etc/init.d && chmod 755 solr
-# cd /etc/rc3.d && ln -s ../init.d/ezpublish S70ezpublish
-# cd /etc/rc5.d && ln -s ../init.d/ezpublish S70ezpublish
-# cd /etc/rc3.d && ln -s ../init.d/ezpublish K70ezpublish
-# cd /etc/rc5.d && ln -s ../init.d/ezpublish K70ezpublish
+# chkconfig:   2345 86 14
+# description: eZ Publish asychronous publishing init script for RHEL and SLES
 
-DESC="eZ Publish asynchronous publishing"
-NAME="ezpqp"
-SYS_ID=ezpublish-async-engineering
-EZ_HOME="/var/www/html/ezpublish" # Set solr home here (example: /var/www/ezpublish/extension/ezfind/java)
-BIN_PATH=$EZ_HOME/bin/php/publishingqueueprocessor.php
-PID_FILE="$EZ_HOME/var/run/asynchronous-publishing.pid"
-USER=apache
-OPTIONS="-n"
+### BEGIN INIT INFO
+# Provides: ezpqp
+# Required-Start: $local_fs $network 
+# Required-Stop: $local_fs $network 
+# Default-Start: 3 4 5
+# Default-Stop: 0 1 2 6
+# Short-Description: start and stop ezpqp
+# Description: eZ Publish asychronous publishing init script for RHEL and SLES
+### END INIT INFO
 
-source /etc/rc.d/init.d/functions
+### Configuration
 
-RETVAL=0
+# eZ Publish install directory
+ezhome="/var/www/html/ezpublish"
 
-d_start() {
-    CURRENT_DIR=`pwd`
-    cd $EZ_HOME
-    daemon --user=$USER --check $NAME $BIN_PATH $OPTIONS > /dev/null 2>&1 &
-    # daemon --user=$USER --check $NAME $BIN_PATH $OPTIONS
-    RETVAL=$?
-    cd $CURRENT_DIR
-    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$NAME
-    return $RETVAL
+# User to run as. Your webserver user, usually
+user="apache"
+
+### End configuration
+
+exec="bin/php/publishingqueueprocessor.php"
+prog=`basename $0`
+pidfolder="/var/run/ezpublish"
+pidfile="$pidfolder/$prog.pid"
+lockfile="/var/lock/subsys/$prog"
+options="-n -p $pidfile"
+
+# Source function library.
+if [ -f /etc/init.d/functions ]; then
+# Red Hat
+  . /etc/init.d/functions
+elif [ -f /lib/lsb/init-functions ]; then
+# LSB, SLES, ..
+  . /lib/lsb/init-functions
+  alias daemon=start_daemon
+  alias status=MyStatus
+else
+  echo "Error: your platform is not supported by $prog" > /dev/stderr
+  exit 1
+fi
+
+if [ ! -d "${pidfolder}" ]; then
+    mkdir "${pidfolder}"
+    chown $user "${pidfolder}"
+fi
+
+start() {
+    [ -x $ezhome/$exec ] || exit 5
+    echo -n $"Starting $prog: "
+    curr_dir=`pwd`
+    cd $ezhome
+    daemon --user $user --check $prog --pidfile $pidfile $exec $options
+    retval=$?
+    echo
+    cd $curr_dir
+    [ $retval -eq 0 ] && touch $lockfile
+    return $retval
 }
 
-d_stop() {
-    kill -TERM `cat $PID_FILE` >> /dev/null 2&>1
-    RETVAL=$?
-    [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$NAME && rm -f $PID_FILE
-    return $RETVAL
+stop() {
+    echo -n $"Stopping $prog: "
+    killproc -p $pidfile $prog
+    retval=$?
+    echo
+    [ $retval -eq 0 ] && rm -f $lockfile
+    return $retval
 }
 
-d_restart() {
-    d_stop >> /dev/null 2&>1
-    sleep 1
-    d_start >> /dev/null 2&>1
+restart() {
+    stop
+    start
 }
 
-d_reload() {
-    killproc -p $PID_FILE -HUP 2&>1
-    RETVAL=$?
-    return $RETVAL
+reload() {
+    restart
+}
+
+force_reload() {
+    restart
 }
 
 d_status() {
-    status -p $PID_FILE $BIN_NAME >> /dev/null 2&>1
-    return $?
+    status -p $pidfile $prog
 }
 
-case "$1" in
-  start)
-    echo " * Starting $DESC ($NAME)"
-    d_status
-    if [ $? -eq 0 ]
-    then
-      echo "   ...already running."
-    else
-      if d_start
-      then
-        echo "   ...done."
-      else
-        echo "   ...failed."
-        RETVAL=1
-      fi
-    fi
-    ;;
-  stop)
-    echo " * Stopping $DESC ($NAME)"
-    if d_stop
-    then
-      echo "   ...done."
-    else
-      echo "   ...failed."
-      RETVAL=1
-    fi
-    ;;
-  restart)
-    echo " * Restarting $DESC ($NAME)"
-    d_status
-    if [ $? -ne 0 ]
-    then
-      echo "   ...not running."
-      RETVAL=1
-    else
-      if d_restart
-      then
-        echo " * ...done."
-      else
-        echo " * ...failed."
-        RETVAL=1
-      fi
-    fi
-    ;;
-  reload)
-    echo " * Reloading $DESC ($NAME): "
-    d_reload
-    echo "   ...done."
-    ;;
-  status)
-    d_status
-    if [ $? -eq 0 ]
-    then
-      echo " * $DESC ($NAME) is running"
-    else
-      echo " * $DESC ($NAME) is not running"
-    fi
-    ;;
-  *)
-    echo $"Usage: $0 {start|stop|restart|reload|status}"
-    RETVAL=1
-esac
+d_status_q() {
+    d_status >/dev/null 2>&1
+}
 
-exit $RETVAL
+
+case "$1" in
+    start)
+        d_status_q && exit 0
+        $1
+        ;;
+    stop)
+        d_status_q || exit 0
+        $1
+        ;;
+    restart)
+        $1
+        ;;
+    reload)
+        d_status_q || exit 7
+        $1
+        ;;
+    force-reload)
+        force_reload
+        ;;
+    status)
+        d_status
+        ;;
+    condrestart|try-restart)
+        d_status_q || exit 0
+        restart
+        ;;
+    *)
+        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
+        exit 2
+esac
+exit $?
+
